export const FETCH_LIST = 'FETCH_LIST'
export const RECEIVE_LIST_SUCCESS = 'RECEIVE_LIST_SUCCESS'
export const RECEIVE_LIST_ERROR = 'RECEIVE_LIST_ERROR'

export const FETCH_LOGIN = 'FETCH_LOGIN'
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS'
export const FETCH_LOGIN_ERROR = 'FETCH_LOGIN_ERROR'
